name: Update DockerHub Allowed Repos

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 1 * *'  # Run at 00:00 on the 1st of every month

jobs:
  update-allowed-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run DockerHub filter script
        run: |
          python dockerhub_filter.py dockerhub_filter_config.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add allowed_repos.yaml all_repos.yaml
          git diff --cached --quiet || git commit -m 'Update allowed and all DockerHub repo lists [auto]'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
